version: '3.3'
services:
  authentik:
    image: ghcr.io/goauthentik/server:2024.2.1
    container_name: authentik
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL_HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL_PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL_USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL_PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_EMAIL_USE_TLS}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL_FROM}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL_PASSWORD}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
    volumes:
      - authentik-media:/media
      - authentik-custom-templates:/custom-templates
      - authentik-certs:/certs
    networks:
      - mynetwork
    depends_on:
      - postgresql
      - redis
    restart: unless-stopped

  postgresql:
    image: postgres:15-alpine
    container_name: authentik-postgresql
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRESQL_PASSWORD}
      POSTGRES_DB: authentik
    volumes:
      - authentik-postgresql:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: authentik-redis
    networks:
      - mynetwork
    restart: unless-stopped

volumes:
  authentik-media:
  authentik-custom-templates:
  authentik-certs:
  authentik-postgresql:

networks:
  mynetwork:
    external: true 