name: nginx
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - mynetwork
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./www/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  letsencrypt:

networks:
  mynetwork:
    external: true